// Code generated by candi v1.20.0.

package repository

import (
	"context"

	"monorepo/services/core/internal/modules/officer/domain"
	shareddomain "monorepo/services/core/pkg/shared/domain"

	"github.com/golangid/candi/candishared"
)

// OfficerRepository abstract interface
type OfficerRepository interface {
	FetchAll(ctx context.Context, filter *domain.FilterOfficer) ([]shareddomain.Officer, error)
	Count(ctx context.Context, filter *domain.FilterOfficer) int
	Find(ctx context.Context, filter *domain.FilterOfficer) (shareddomain.Officer, error)
	Save(ctx context.Context, data *shareddomain.Officer, updateOptions ...candishared.DBUpdateOptionFunc) error
	Delete(ctx context.Context, filter *domain.FilterOfficer) (err error)
}
