// Code generated by candi v1.20.0.

package usecase

import (
	"context"

	"monorepo/services/core/internal/modules/officer/domain"
	"monorepo/services/core/pkg/shared/repository"
	"monorepo/services/core/pkg/shared/usecase/common"

	"github.com/golangid/candi/codebase/factory/dependency"
)

// OfficerUsecase abstraction
type OfficerUsecase interface {
	GetAllOfficer(ctx context.Context, filter *domain.FilterOfficer) (data domain.ResponseOfficerList, err error)
	GetDetailOfficer(ctx context.Context, id int) (data domain.ResponseOfficer, err error)
	CreateOfficer(ctx context.Context, data *domain.RequestOfficer) (res domain.ResponseOfficer, err error) 
	UpdateOfficer(ctx context.Context, data *domain.RequestOfficer) (err error)
	DeleteOfficer(ctx context.Context, id int) (err error)
}

type officerUsecaseImpl struct {
	deps          dependency.Dependency
	sharedUsecase common.Usecase
	repoSQL       repository.RepoSQL
	// repoMongo     repository.RepoMongo
}

// NewOfficerUsecase usecase impl constructor
func NewOfficerUsecase(deps dependency.Dependency) (OfficerUsecase, func(sharedUsecase common.Usecase)) {
	uc := &officerUsecaseImpl{
		deps:    deps,
		repoSQL:   repository.GetSharedRepoSQL(),
		// repoMongo: repository.GetSharedRepoMongo(),
		
	}
	return uc, func(sharedUsecase common.Usecase) {
		uc.sharedUsecase = sharedUsecase
	}
}
