// Code generated by candi v1.20.0. DO NOT EDIT.

package sdk

import (
	"sync"

	// @candi:serviceImport
	"monorepo/sdk/core"
)

// Option func type
type Option func(*sdkInstance)

var (
	sdk  SDK
	once sync.Once
)

// SetGlobalSDK constructor with each sdk service option.
func SetGlobalSDK(opts ...Option) {
	s := new(sdkInstance)
	for _, o := range opts {
		o(s)
	}
	once.Do(func() {
		sdk = s
	})
}

// GetSDK get global sdk instance
func GetSDK() SDK {
	return sdk
}

// @candi:construct

// SetCore option func
func SetCore(core core.Core) Option {
	return func(s *sdkInstance) {
		s.core = core
	}
}

// SDK instance abstraction
type SDK interface {
	// @candi:serviceMethod
	Core() core.Core
}

// sdkInstance implementation
type sdkInstance struct {
	// @candi:serviceField
	core	core.Core
}

// @candi:instanceMethod
func (s *sdkInstance) Core() core.Core {
	return s.core
}
