// Code generated by candi v1.20.0.

package usecase

import (
	"context"

	"monorepo/services/core/internal/modules/policy/domain"
	"monorepo/services/core/pkg/shared/repository"
	"monorepo/services/core/pkg/shared/usecase/common"

	"github.com/golangid/candi/codebase/factory/dependency"
)

// PolicyUsecase abstraction
type PolicyUsecase interface {
	GetAllPolicy(ctx context.Context, filter *domain.FilterPolicy) (data domain.ResponsePolicyList, err error)
	GetDetailPolicy(ctx context.Context, id int) (data domain.ResponsePolicy, err error)
	CreatePolicy(ctx context.Context, data *domain.RequestPolicy) (res domain.ResponsePolicy, err error) 
	UpdatePolicy(ctx context.Context, data *domain.RequestPolicy) (err error)
	DeletePolicy(ctx context.Context, id int) (err error)
}

type policyUsecaseImpl struct {
	deps          dependency.Dependency
	sharedUsecase common.Usecase
	repoSQL       repository.RepoSQL
	// repoMongo     repository.RepoMongo
}

// NewPolicyUsecase usecase impl constructor
func NewPolicyUsecase(deps dependency.Dependency) (PolicyUsecase, func(sharedUsecase common.Usecase)) {
	uc := &policyUsecaseImpl{
		deps:    deps,
		repoSQL:   repository.GetSharedRepoSQL(),
		// repoMongo: repository.GetSharedRepoMongo(),
		
	}
	return uc, func(sharedUsecase common.Usecase) {
		uc.sharedUsecase = sharedUsecase
	}
}
