// Code generated by candi v1.20.0.

package usecase

import (
	"sync"

	// @candi:usecaseImport
	policyusecase "monorepo/services/core/internal/modules/policy/usecase"
	officerusecase "monorepo/services/core/internal/modules/officer/usecase"
	claimusecase "monorepo/services/core/internal/modules/claim/usecase"
	"monorepo/services/core/pkg/shared/usecase/common"

	"github.com/golangid/candi/codebase/factory/dependency"
)

type (
	// Usecase unit of work for all usecase in modules
	Usecase interface {
		// @candi:usecaseMethod
		Policy() policyusecase.PolicyUsecase
		Officer() officerusecase.OfficerUsecase
		Claim() claimusecase.ClaimUsecase
	}

	usecaseUow struct {
		// @candi:usecaseField
		policyusecase.PolicyUsecase
		officerusecase.OfficerUsecase
		claimusecase.ClaimUsecase
	}
)

var usecaseInst *usecaseUow
var once sync.Once

// SetSharedUsecase set singleton usecase unit of work instance
func SetSharedUsecase(deps dependency.Dependency) {
	once.Do(func() {
		usecaseInst = new(usecaseUow)
		var setSharedUsecaseFuncs []func(common.Usecase)
		var setSharedUsecaseFunc func(common.Usecase)

		// @candi:usecaseCommon
		usecaseInst.PolicyUsecase, setSharedUsecaseFunc = policyusecase.NewPolicyUsecase(deps)
		setSharedUsecaseFuncs = append(setSharedUsecaseFuncs, setSharedUsecaseFunc)
		usecaseInst.OfficerUsecase, setSharedUsecaseFunc = officerusecase.NewOfficerUsecase(deps)
		setSharedUsecaseFuncs = append(setSharedUsecaseFuncs, setSharedUsecaseFunc)
		usecaseInst.ClaimUsecase, setSharedUsecaseFunc = claimusecase.NewClaimUsecase(deps)
		setSharedUsecaseFuncs = append(setSharedUsecaseFuncs, setSharedUsecaseFunc)

		sharedUsecase := common.SetCommonUsecase(usecaseInst)
		for _, setFunc := range setSharedUsecaseFuncs {
			setFunc(sharedUsecase)
		}
	})
}

// GetSharedUsecase get usecase unit of work instance
func GetSharedUsecase() Usecase {
	return usecaseInst
}

// @candi:usecaseImplementation
func (uc *usecaseUow) Policy() policyusecase.PolicyUsecase {
	return uc.PolicyUsecase
}

func (uc *usecaseUow) Officer() officerusecase.OfficerUsecase {
	return uc.OfficerUsecase
}

func (uc *usecaseUow) Claim() claimusecase.ClaimUsecase {
	return uc.ClaimUsecase
}

