// Code generated by candi v1.20.0.

package repository

import (
	"context"

	"monorepo/services/core/internal/modules/policy/domain"
	shareddomain "monorepo/services/core/pkg/shared/domain"

	"github.com/golangid/candi/candishared"
)

// PolicyRepository abstract interface
type PolicyRepository interface {
	FetchAll(ctx context.Context, filter *domain.FilterPolicy) ([]shareddomain.Policy, error)
	Count(ctx context.Context, filter *domain.FilterPolicy) int
	Find(ctx context.Context, filter *domain.FilterPolicy) (shareddomain.Policy, error)
	Save(ctx context.Context, data *shareddomain.Policy, updateOptions ...candishared.DBUpdateOptionFunc) error
	Delete(ctx context.Context, filter *domain.FilterPolicy) (err error)
}
